#!/usr/bin/env python3
"""
playing with color
"""
import os
import colorama


if 'PYCHARM_HOSTED' in os.environ:
    convert = False  # in PyCharm, we should disable convert
    strip = False
    print("Hi! You are using PyCharm")
else:
    convert = None
    strip = None

colorama.init(convert=convert, strip=strip)
print(colorama.Fore.GREEN + ":)" + colorama.Fore.RESET)
print(colorama.Fore.RED + ":(" + colorama.Fore.RESET)
